# Generated by Django 3.2.23 on 2025-12-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('climate', models.CharField(default='unknown', max_length=50)),
                ('peril_rating', models.CharField(default='unknown', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
