# Generated by Django 3.2.23 on 2025-12-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biome',
            name='magic_level',
            field=models.CharField(blank=True, default='unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biome',
            name='climate',
            field=models.CharField(blank=True, default='unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biome',
            name='peril_rating',
            field=models.CharField(blank=True, default='unknown', max_length=50, null=True),
        ),
    ]
