# Generated by Django 4.2.27 on 2026-03-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biomes", "0002_auto_20251203_1320"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biome",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
